version: "3"

services:
  beget-dyndns:
    image: riuson/beget-dyndns
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BEGET_LOGIN: "${BEGET_LOGIN}"
      BEGET_PASSW: "${BEGET_PASSW}"
      DOMAINS: "${DOMAINS}"
      GET_IP_URL: "${GET_IP_URL}"
    restart: always
    stop_grace_period: 1m
